### ISSUE TITLE
Engenharia de Requisitos

### ISSUE THREAD

**Issue by JoelSRangel** [fga-eps-mds/2023.1-DAB#5]
## DESCRIÇÃO
A engenharia de requisitos é uma das fases mais importantes do desenvolvimento de software. É nessa fase que os requisitos do cliente são coletados, analisados e documentados para orientar todo o processo de desenvolvimento do software. No entanto, muitas vezes essa fase é negligenciada ou mal executada, resultando em atrasos, custos adicionais e até mesmo falhas do projeto. Desta forma e de extrema importância o estudo de técnicas de elicitação de requisitos.

## OBJETIVO
Aprender as melhores práticas de engenharia de requisitos para garantir o sucesso de projetos de software.

### Estudo dos conceitos relacionados a:

- [x] Identificação dos stakeholders;
- [x] Seleção das técnicas de elicitação de requisitos;
- [x] Realização das técnicas de elicitação;
- [x] Análise e validação dos requisitos;
- [x] Priorização dos requisitos;
- [x] Documentação dos requisitos.

## TEMPO ESTIMADO
Esta tarefa pode ser concluída em uma semana, dependendo do tempo dedicado e do desenvolvimento individual.

**Comment by Mayara-tech** [comment]
DESCRIÇÃO: A engenharia de requisitos é uma das fases mais importantes do desenvolvimento de software. É nessa fase que os requisitos do cliente são coletados, analisados e documentados para orientar todo o processo de desenvolvimento do software. No entanto, muitas vezes essa fase é negligenciada ou mal executada, resultando em atrasos, custos adicionais e até mesmo falhas do projeto. Desta forma e de extrema importância o estudo de técnicas de elicitação de requisitos.

TAREFAS: Estudo dos conceitos relacionados a:

- [ ] Identificação dos stakeholders;
- [ ] Seleção das técnicas de elicitação de requisitos;
- [ ] Realização das técnicas de elicitação;
- [ ] Análise e validação dos requisitos;
- [ ] Priorização dos requisitos;
- [ ] Documentação dos requisitos.
