### ISSUE TITLE
Qualidade do código frontend

### ISSUE THREAD

**Issue by brenob6** [fga-eps-mds/2023.1-DAB#68]
### Descrição

O Estlint está apontando vários problemas no código frontend. O objetivo dessa issue é sanar esses problemas

Serão discutidos os seguintes tópicos nesta tarefa:

- Melhoria da qualidade do código

### Critérios de aceitação

- [x] o PR deve ser aprovado pelo Action lint.

### Tarefas

- [x] Melhorar a avaliação do código para ser aceito pelo Estlint.

**Comment by evinhassoft** [comment]
Se precisar de ajuda, me avisa!
