### ISSUE TITLE
[BUG] As opções do menu não estão funcionando

### ISSUE THREAD

**Issue by MillenaQueiroz** [fga-eps-mds/2023.1-DAB#70]
**Describe the bug**
Ao clicar nas opcões do menu não temos nenhum redirecionamento ou ação. 

**To Reproduce**
1. Rode o projeto angular
2. Clique em "Recursos"
3. Veja o erro

**Expected behavior**
É necessário que ao clicar nas opções o usuário seja redirecionado a página correspondente.

**Screenshots**
![image](https://github.com/fga-eps-mds/2023.1-DAB/assets/60625345/4a6f21d9-3ba5-4502-9d2f-e9de6a5b73ce)

**Desktop (please complete the following information):**

**Comment by evinhassoft** [comment]
Boa, tudo certo. vou dar merge na master
