### ISSUE TITLE
Fix componente mapa

### ISSUE THREAD

**Issue by brenob6** [fga-eps-mds/2023.1-DAB#76]
### Descrição

O mapa não está centralizado e existe um bug que deixa os Estados pretos.

![image](https://github.com/fga-eps-mds/2023.1-DAB/assets/72840950/9e352a75-c3fe-4c33-bd39-73e07b4737f1)

O mapa também não está responsivo.

### Tarefas

- [x] Centralizar o mapa
- [ ] Arrumar o bug que deixa o mapa preto
- [x] Arrumar responsividade

**Comment by evinhassoft** [comment]
Conseguimos centralizar o mapa e arrumar a responsividade do mesmo, entretanto, descobrimos que o problema que deixa o mapa preto trata-se de um bug no CSS interpretado pelo navegador. O navegador Firefox não nos apresentou qualquer tipo de bug.
