### ISSUE TITLE
Feature mudar tipo de gráfico

### ISSUE THREAD

**Issue by brenob6** [fga-eps-mds/2023.1-DAB#78]
### Descrição

Todos os gráficos estão no formato de barra. Pode ser interessante utilizar outro formato de gráfico para alguns tipos de dados. Para isso, é útil criar um botão para o usuário escolher qual tipo de gráfico ele deseja utilizar na análise dos dados.

### Critérios de aceitação

- [x] O usuário deve ser capaz de escolher o tipo de gráfico.

### Tarefas

- [x] Desenvolver uma forma de alterar a forma dos gráficos.

**Comment by evinhassoft** [comment]
Foi concluído e estilizei os botões!

![image](https://github.com/fga-eps-mds/2023.1-DAB/assets/88348712/570fb6bf-1910-4254-a8c0-20943bdb621c)
